# Generated by Django 2.2.4 on 2022-08-09 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0002_auto_20220808_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('startingdate', models.DateField()),
                ('endingdate', models.DateField()),
                ('project', models.ForeignKey(default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='dropship.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropship.Issue')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropship.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
